Repository FashionForecast/FashionForecast-client, pull requests merged in 2024-09, with the labels that each got.

#53 기타 옷차림 문구 수정
  src/pages/Home/components/RecommendClothes.tsx
Labels: 🐤frontend

#55 옷차림 이미지 로직 리팩토링
  src/assets/clothesImage/clothesImage.ts
  src/pages/Home/components/RecommendClothes.tsx
Labels: 🐤frontend, 🛠️refactor

#51 Feature/#47 time selector 디자인
  src/components/icon/Check/index.tsx
  src/pages/Home/components/TimeSelector.style.ts
  src/pages/Home/components/TimeSelector.tsx
  src/pages/Home/components/weather/CardSummary.style.ts
  src/pages/Home/style.ts
Labels: 🐤frontend, ✨feature

#57 버그 수정 및 변경 사항 반영
  src/assets/clothesImage/clothesImage.ts
  src/components/icon/Check/index.tsx
  src/pages/Home/components/RecommendClothes.tsx
  src/pages/Home/components/TimeSelector.style.ts
  src/pages/Home/components/TimeSelector.tsx
  src/pages/Home/components/WeatherTimeLine.tsx
  src/styles/theme.ts
Labels: 🐛bug, 🐤frontend

#59 WeatherCard 변경 및 옷차림 이미지 추가
  src/assets/clothesImage/clothesImage.ts
  src/assets/clothesImage/겉옷장우산.svg
  src/assets/clothesImage/겉옷접이식우산.svg
  src/pages/Home/components/RecommendClothes.tsx
  src/pages/Home/components/weather/WeatherCard.style.ts
  src/pages/Home/components/weather/WeatherCard.tsx
Labels: 🐤frontend, ✨feature

#60 A2HS 구현
  index.html
  public/icon-192.svg
  public/icon-512.svg
  public/manifest.webmanifest
  src/components/layout/RootLayout/components/A2hsSnackbar.style.ts
  src/components/layout/RootLayout/components/A2hsSnackbar.tsx
  src/components/layout/RootLayout/hooks/useA2HS.tsx
  src/components/layout/RootLayout/index.tsx
  src/types/global.d.ts
Labels: ✨feature

#63 Fix/#62 시간선택 오류
  src/pages/Home/components/TimeSelector.tsx
Labels: 🐛bug, 🐤frontend

#64 온도 옵션 disabled 조건 변경
  src/pages/Home/components/RecommendClothes.style.ts
  src/pages/Home/components/RecommendClothes.tsx
Labels: ✨feature

#70 time selector 리팩토링
  src/components/icon/Hyphen/index.tsx
  src/constants/timeSelector/data.ts
  src/pages/Home/components/TimeCarousel.style.ts
  src/pages/Home/components/TimeCarousel.tsx
  src/pages/Home/components/TimeSelector.style.ts
  src/pages/Home/components/TimeSelector.tsx
  src/pages/Home/index.tsx
  src/service/weather.ts
  src/utils/date.ts
  src/utils/formatToISOString.ts
  src/utils/time.tsx
Labels: ✨feature, 🛠️refactor

#71 강수확률 이미지 및 time selector 모바일 오류 수정
  src/assets/pcpImage/PClear.svg
  src/assets/pcpImage/PRain.svg
  src/assets/pcpImage/PRaindrop.svg
  src/assets/pcpImage/pcpImage.ts
  src/assets/popImage/Pop_0.svg
  src/assets/popImage/Pop_10.svg
  src/assets/popImage/Pop_100.svg
  src/assets/popImage/Pop_20.svg
  src/assets/popImage/Pop_30.svg
  src/assets/popImage/Pop_40.svg
  src/assets/popImage/Pop_50.svg
  src/assets/popImage/Pop_60.svg
  src/assets/popImage/Pop_70.svg
  src/assets/popImage/Pop_80.svg
  src/assets/popImage/Pop_90.svg
  src/assets/popImage/popImage.ts
  src/assets/tempImage/Cold.svg
  src/assets/tempImage/Cool.svg
  src/assets/tempImage/Hot.svg
  src/assets/tempImage/Moderate.svg
  src/assets/tempImage/Warm.svg
  src/assets/tempImage/tempImage.ts
  src/pages/Home/components/TimeCarousel.style.ts
  src/pages/Home/components/TimeCarousel.tsx
  src/pages/Home/components/weather/HandlePcp.tsx
  src/pages/Home/components/weather/HandlePop.tsx
  src/pages/Home/components/weather/HandleTemp.tsx
  src/pages/Home/components/weather/HandleWeather.tsx
  src/pages/Home/components/weather/WeatherCard.tsx
Labels: 🐛bug

#72 소셜 로그인 기본 구조
  src/pages/Home/components/Header/index.tsx
  src/pages/Login/index.tsx
  src/pages/LoginAuth/index.tsx
  src/routes.tsx
  src/service/clothes.ts
  src/service/login.ts
  src/service/search.ts
  src/service/weather.ts
  vite.config.ts
Labels: ✨feature

#77 비회원 기능 배포를 위한 작업
  src/components/GoBackButton/index.tsx
  src/pages/Feedback/index.tsx
  src/pages/Feedback/style.ts
  src/pages/Home/components/Header/index.tsx
  src/pages/Search/components/SearchHeader/index.tsx
  src/pages/Search/components/SearchHeader/style.ts
  src/routes.tsx
  src/styles/theme.ts
Labels: ✨feature

#80 메인페이지 로딩 UI 및 지역 검색 버그 수정
  package-lock.json
  src/pages/Home/components/RecommendClothes/index.tsx
  src/pages/Home/components/RecommendClothes/loading.tsx
  src/pages/Home/components/WeatherCard/index.tsx
  src/pages/Home/components/WeatherTimeLine/index.tsx
  src/pages/Home/index.tsx
  src/pages/Home/loading.tsx
  src/pages/Search/components/RecentSearchList/index.tsx
  src/service/clothes.ts
  src/service/weather.ts
  src/types/clothes.ts
  src/types/weather.ts
Labels: 🐛bug, ✨feature

#82 geolocation 리팩토링
  src/components/layout/RootLayout/index.tsx
  src/hooks/useGeolocation.tsx
  src/pages/Home/components/Header/index.tsx
  src/pages/Home/components/RecommendClothes/index.tsx
  src/pages/Home/index.tsx
  src/pages/Search/components/CurrentRegionButton/index.tsx
  src/pages/Search/components/Index/RegionItem/index.tsx
  src/pages/Search/components/RecentSearchList/index.tsx
  src/pages/Search/components/RegionItem.style.ts
  src/pages/Search/components/RegionItem.tsx
  src/redux/slice/EXAMPLE_counterSlice.ts
  src/redux/slice/currentRegionSlice.ts
  src/redux/slice/geolocationSlice.ts
  src/redux/store.ts
Labels: 🛠️refactor

#84 네트워크 오류 처리 및 NotFound 페이지 스타일 적용
  src/components/CustomMui/CustomButton.tsx
  src/components/NetworkError/index.tsx
  src/components/layout/RootLayout/components/A2hsSnackbar/index.tsx
  src/pages/Feedback/index.tsx
  src/pages/Feedback/style.ts
  src/pages/Home/components/Header/index.tsx
  src/pages/Home/components/RecommendClothes/index.tsx
  src/pages/Home/components/TimeSelector/index.tsx
  src/pages/Home/components/TimeSelector/style.ts
  src/pages/Home/index.tsx
  src/pages/NotFound/index.tsx
Labels: ✨feature

#86 시간 변경 시, 추천 옷차림이 변하지 않는 오류 수정
  src/pages/Home/components/RecommendClothes/index.tsx
  src/pages/Home/components/TimeSelector/index.tsx
Labels: 🐛bug

#88 google analytics 적용
  index.html
Labels: ✨feature

#89 1.0.0 버전 배포
  index.html
  package-lock.json
  package.json
  src/components/CustomMui/CustomButton.tsx
  src/components/NetworkError/index.tsx
  src/components/layout/RootLayout/components/A2hsSnackbar/index.tsx
  src/components/layout/RootLayout/index.tsx
  src/hooks/useGeolocation.tsx
  src/pages/Feedback/index.tsx
  src/pages/Feedback/style.ts
  src/pages/Home/components/Header/index.tsx
  src/pages/Home/components/RecommendClothes/index.tsx
  src/pages/Home/components/RecommendClothes/loading.tsx
  src/pages/Home/components/TimeSelector/index.tsx
  src/pages/Home/components/TimeSelector/style.ts
  src/pages/Home/components/WeatherCard/index.tsx
  src/pages/Home/components/WeatherTimeLine/index.tsx
  src/pages/Home/index.tsx
  src/pages/Home/loading.tsx
  src/pages/NotFound/index.tsx
  src/pages/Search/components/CurrentRegionButton/index.tsx
  src/pages/Search/components/Index/RegionItem/index.tsx
  src/pages/Search/components/RecentSearchList/index.tsx
  src/pages/Search/components/RegionItem.style.ts
  src/pages/Search/components/RegionItem.tsx
  src/redux/slice/EXAMPLE_counterSlice.ts
  src/redux/slice/geolocationSlice.ts
  src/redux/store.ts
  src/service/clothes.ts
  src/service/weather.ts
  src/types/clothes.ts
  src/types/weather.ts
Labels: deploy
