Repository FashionForecast/FashionForecast-client, pull requests merged in 2024-08, with the labels that each got.

#3 초기 환경 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc.json
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  index.html
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.module.scss
  src/App.tsx
  src/_colors.scss
  src/assets/react.svg
  src/index.scss
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🐤frontend

#5 stylelint 설정 변경
  .stylelintrc.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
Labels: 🐤frontend

#7 라이브러리 설정
  .stylelintrc.json
  .vscode/settings.json
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.module.scss
  src/App.tsx
  src/_colors.scss
  src/assets/react.svg
  src/components/EXAMPLE_TEXT/index.tsx
  src/components/EXAMPLE_TEXT/style.ts
  src/contexts/ReduxProvider.tsx
  src/contexts/TanstackQueryProvider.tsx
  src/hooks/useAppDispatch.ts
  src/hooks/useAppSelector.ts
  src/index.scss
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/NotFound/index.tsx
  src/redux/slice/EXAMPLE_counterSlice.ts
  src/redux/store.ts
  src/routes.tsx
  src/styles/normalize.css
  src/styles/reset.css
  vite.config.ts
Labels: 🐤frontend

#9 배포 환경에서 백엔드와 통신 코드 테스트
  .github/workflows/cicd.yml
  .gitignore
  README.md
  src/pages/Home/index.tsx
  src/service/weather.ts
  src/types/weather.ts
Labels: 🐤frontend

#11 위치별 좌표 파일 생성 스크립트 작성
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
  script/region.cjs
  src/assets/react.svg
  src/assets/region.json
Labels: 🐤frontend

#14 지역 음절 단위 검색 구현
  .stylelintrc.json
  public/vite.svg
  script/region.cjs
  src/App.module.scss
  src/App.tsx
  src/_colors.scss
  src/assets/region.json
  src/components/EXAMPLE_TEXT/index.tsx
  src/components/EXAMPLE_TEXT/style.ts
  src/components/icon/Arrow/index.tsx
  src/components/icon/Cancel/index.tsx
  src/components/icon/Check/index.tsx
  src/components/layout/RootLayout/index.tsx
  src/components/layout/RootLayout/style.ts
  src/index.scss
  src/pages/Home/index.tsx
  src/pages/Search/components/RegionItem.style.ts
  src/pages/Search/components/RegionItem.tsx
  src/pages/Search/index.tsx
  src/pages/Search/style.ts
  src/routes.tsx
  src/styles/reset.css
Labels: 🐤frontend, ✨feature

#17 프로젝트 theme 스타일 설정
  src/contexts/EmotionThemeProvider.tsx
  src/contexts/MuiThemeProvider.tsx
  src/main.tsx
  src/styles/colors.ts
  src/styles/font.css
  src/styles/reset.css
  src/styles/theme.ts
  src/styles/typo.ts
  src/types/emotion.d.ts
Labels: 🐤frontend, ✨feature

#21 날씨 호출 기준 현재 시간으로 변경(#19)
  src/service/weather.ts
Labels: 🐤frontend

#27 mui base 컴포넌트 구현 및 스타일 네임스페이스 구체화
  src/components/CustomAppBar/index.tsx
  src/components/CustomTextField/index.tsx
  src/components/CustomToolBar/index.tsx
  src/pages/Home/components/RegionButton.style.ts
  src/pages/Home/components/RegionButton.tsx
  src/pages/Home/components/RegionSelector.style.ts
  src/pages/Home/components/RegionSelector.tsx
  src/pages/Search/components/RegionItem.style.ts
  src/pages/Search/components/RegionItem.tsx
  src/pages/Search/index.tsx
  src/pages/Search/style.ts
Labels: 🐤frontend

#29 게스트 로그인 구현
  src/components/layout/RootLayout/index.tsx
  src/constants/localStorage/key.ts
  src/service/login.ts
  src/types/login.ts
Labels: 🐤frontend, ✨feature

#34 메인 페이지 Header의 위치 기능 구현
  script/region.cjs
  src/assets/region.json
  src/components/CustomButton/index.tsx
  src/components/CustomPaper/index.tsx
  src/components/icon/Account/index.tsx
  src/components/icon/Triangle/index.tsx
  src/pages/Home/components/Header.tsx
  src/pages/Home/components/hooks/useGeolocation.tsx
  src/pages/Home/index.tsx
  src/pages/Search/index.tsx
Labels: 🐤frontend, ✨feature

#35 Feature/#13-기상정보-카드-컨텐츠
  src/components/icon/Pcp/PClear.svg
  src/components/icon/Pcp/PRain.svg
  src/components/icon/Pcp/PRaindrop.svg
  src/components/icon/Pop/Pop_0.svg
  src/components/icon/Pop/Pop_10.svg
  src/components/icon/Pop/Pop_100.svg
  src/components/icon/Pop/Pop_20.svg
  src/components/icon/Pop/Pop_30.svg
  src/components/icon/Pop/Pop_40.svg
  src/components/icon/Pop/Pop_50.svg
  src/components/icon/Pop/Pop_60.svg
  src/components/icon/Pop/Pop_70.svg
  src/components/icon/Pop/Pop_80.svg
  src/components/icon/Pop/Pop_90.svg
  src/components/icon/Temperature/Cold.svg
  src/components/icon/Temperature/Cool.svg
  src/components/icon/Temperature/Hot.svg
  src/components/icon/Temperature/Moderate.svg
  src/components/icon/Temperature/Warm.svg
  src/components/icon/Weather/Cloudy.svg
  src/components/icon/Weather/DayClear.svg
  src/components/icon/Weather/DayPartlyCloudy.svg
  src/components/icon/Weather/NightClear.svg
  src/components/icon/Weather/NightPartlyCloudy.svg
  src/components/icon/Weather/RDSnowDrifting.svg
  src/components/icon/Weather/Rain.svg
  src/components/icon/Weather/RainSnow.svg
  src/components/icon/Weather/Raindrop.svg
  src/components/icon/Weather/Shower.svg
  src/components/icon/Weather/Snow.svg
  src/components/icon/Weather/SnowDrifting.svg
  src/pages/Home/components/weather/CardSummary.style.ts
  src/pages/Home/components/weather/HandlePcp.tsx
  src/pages/Home/components/weather/HandlePop.tsx
  src/pages/Home/components/weather/HandleTemp.tsx
  src/pages/Home/components/weather/HandleWeather.tsx
  src/pages/Home/components/weather/WeatherCard.tsx
  src/pages/Home/index.tsx
  src/routes.tsx
  src/service/weather.ts
  src/styles/typo.ts
  src/types/weather.ts
Labels: 🐤frontend, ✨feature

#37 검색 기능 변경
  .gitignore
  script/region.cjs
  script/기상청좌표.xlsx
  script/위경도.xlsx
  src/assets/weatherRegionCoordinates.ts
  src/components/icon/Close/index.tsx
  src/components/icon/Location/index.tsx
  src/components/layout/RootLayout/index.tsx
  src/constants/localStorage/key.ts
  src/hooks/useGeolocation.tsx
  src/pages/Home/components/Header.style.ts
  src/pages/Home/components/Header.tsx
  src/pages/Home/components/RegionSelector.style.ts
  src/pages/Home/components/RegionSelector.tsx
  src/pages/Home/components/weather/WeatherCard.tsx
  src/pages/Home/index.tsx
  src/pages/Search/components/RecentSearch.tsx
  src/pages/Search/components/RecentSearchList.style.ts
  src/pages/Search/components/RegionItem.tsx
  src/pages/Search/components/RegionSetButton.style.ts
  src/pages/Search/components/RegionSetButton.tsx
  src/pages/Search/components/SearchHeader.style.ts
  src/pages/Search/components/SearchHeader.tsx
  src/pages/Search/index.tsx
  src/pages/Search/style.ts
  src/redux/slice/EXAMPLE_counterSlice.ts
  src/redux/slice/currentRegionSlice.ts
  src/redux/store.ts
  src/service/weather.ts
  src/types/region.ts
Labels: 🐤frontend, ✨feature

#39 추천 옷차림 컴포넌트 구현
  src/assets/clothesImage/반팔티.svg
  src/components/CustomToggleButton/index.tsx
  src/pages/Home/components/RecommendClothes.style.ts
  src/pages/Home/components/RecommendClothes.tsx
  src/pages/Home/index.tsx
  src/service/clothes.ts
  src/styles/colors.ts
  src/styles/theme.ts
  src/styles/typo.ts
  src/types/clothes.ts
  src/types/weather.ts
Labels: 🐤frontend, ✨feature

#41 최근 검색어 조회/등록/삭제 구현
  src/pages/Search/components/RecentSearch.tsx
  src/pages/Search/components/RegionItem.tsx
  src/pages/Search/index.tsx
  src/service/search.ts
  src/types/search.ts
Labels: 🐤frontend, ✨feature

#42 Feature/#33 time selector 구현
  src/components/icon/Hyphen/index.tsx
  src/pages/Home/components/TimeSelector.style.ts
  src/pages/Home/components/TimeSelector.tsx
  src/pages/Home/index.tsx
  src/service/weather.ts
  src/utils/formatToISOString.ts
  src/utils/time.tsx
Labels: 🐤frontend, ✨feature

#45 Fix/#33 시간 오류 수정
  src/pages/Home/components/TimeSelector.tsx
  src/service/weather.ts
Labels: 🐛bug, 🐤frontend

#46 타임라인 구현
  package.json
  pnpm-lock.yaml
  src/assets/weatherIconImage/DayClear.svg
  src/assets/weatherIconImage/DayCloudy.svg
  src/assets/weatherIconImage/DayImages.ts
  src/assets/weatherIconImage/DayPartlyCloudy.svg
  src/assets/weatherIconImage/DayRain.svg
  src/assets/weatherIconImage/DayRainAndSnow.svg
  src/assets/weatherIconImage/DayRainAndSnowFlurries.svg
  src/assets/weatherIconImage/DayRainDrop.svg
  src/assets/weatherIconImage/DayShower.svg
  src/assets/weatherIconImage/DaySnow.svg
  src/assets/weatherIconImage/DaySnowFlurries.svg
  src/assets/weatherIconImage/NightClear.svg
  src/assets/weatherIconImage/NightCloudy.svg
  src/assets/weatherIconImage/NightImages.ts
  src/assets/weatherIconImage/NightPartlyCloudy.svg
  src/assets/weatherIconImage/NightRain.svg
  src/assets/weatherIconImage/NightRainAndSnow.svg
  src/assets/weatherIconImage/NightRainAndSnowFlurries.svg
  src/assets/weatherIconImage/NightRainDrop.svg
  src/assets/weatherIconImage/NightShower.svg
  src/assets/weatherIconImage/NightSnow.svg
  src/assets/weatherIconImage/NightSnowFlurries.svg
  src/pages/Home/components/WeatherTimeLine.style.ts
  src/pages/Home/components/WeatherTimeLine.tsx
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
  src/styles/theme.ts
  src/types/svg.d.ts
  src/types/weather.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🐤frontend, ✨feature

#50 디자인 변경 사항 반영
  index.html
  public/logo.svg
  src/assets/clothesImage/clothesImage.ts
  src/assets/clothesImage/겉옷.svg
  src/assets/clothesImage/긴팔티.svg
  src/assets/clothesImage/니트.svg
  src/assets/clothesImage/목도리.svg
  src/assets/clothesImage/민소매.svg
  src/assets/clothesImage/바지.svg
  src/assets/clothesImage/반바지.svg
  src/assets/clothesImage/반팔티.svg
  src/assets/clothesImage/장우산.svg
  src/assets/clothesImage/접이식우산.svg
  src/assets/clothesImage/청바지.svg
  src/assets/clothesImage/코트.svg
  src/assets/clothesImage/트렌치코트.svg
  src/assets/clothesImage/패딩.svg
  src/assets/clothesImage/후드티.svg
  src/assets/clothesImage/히트텍.svg
  src/components/CustomTextField/index.tsx
  src/components/CustomToolBar/index.tsx
  src/pages/Home/components/Header.style.ts
  src/pages/Home/components/Header.tsx
  src/pages/Home/components/RecommendClothes.style.ts
  src/pages/Home/components/RecommendClothes.tsx
  src/pages/Home/components/WeatherTimeLine.style.ts
  src/pages/Home/components/WeatherTimeLine.tsx
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
  src/styles/colors.ts
  src/styles/reset.css
  src/styles/theme.ts
  src/types/clothes.ts
Labels: 🐤frontend, ✨feature
